//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnifeProduction.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blade()
        {
            this.Knives = new HashSet<Knives>();
        }
    
        public int id { get; set; }
        public Nullable<int> idObuh { get; set; }
        public Nullable<int> idFalsehood { get; set; }
    
        public virtual Falsehood Falsehood { get; set; }
        public virtual Obuh Obuh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Knives> Knives { get; set; }
    }
}
