//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnifeProduction.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knives
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knives()
        {
            this.OrderKnives = new HashSet<OrderKnives>();
        }
    
        public int id { get; set; }
        public int idBlade { get; set; }
        public int idHandle { get; set; }
        public bool isHole { get; set; }
        public string Name { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Blade Blade { get; set; }
        public virtual Handle Handle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderKnives> OrderKnives { get; set; }
    }
}
