//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnifeProduction.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderKnives
    {
        public int id { get; set; }
        public Nullable<int> idKnives { get; set; }
        public Nullable<int> idUser { get; set; }
        public string Count { get; set; }
        public string Price { get; set; }
    
        public virtual Knives Knives { get; set; }
        public virtual User User { get; set; }
    }
}
